"use client";
import React from "react";
import QuizEngine from "@/app/components/ui/QuizEngine";

const handleNext = () => {
  const questions = [
  {
    "question": "What type of codes are generated by Huffman Coding?",
    "options": [
      "Fixed-length codes",
      "Prefix codes",
      "Hash codes",
      "Postfix codes"
    ],
    "correctAnswer": 1,
    "explanation": "Huffman coding generates prefix codes, meaning no code is a prefix of another code, ensuring unambiguous decoding."
  },
  {
    "question": "Which data structure is primarily used to build a Huffman Tree efficiently?",
    "options": [
      "Stack",
      "Queue",
      "Priority Queue (Min-Heap)",
      "Graph"
    ],
    "correctAnswer": 2,
    "explanation": "A priority queue (typically implemented as a min-heap) is used to efficiently extract the two nodes with the smallest frequencies."
  },
  {
    "question": "In a Huffman Tree, where do the actual characters reside?",
    "options": [
      "At the root node",
      "Only at the internal nodes",
      "Only at the leaf nodes",
      "At any random node"
    ],
    "correctAnswer": 2,
    "explanation": "All characters reside at the leaf nodes of the Huffman Tree. Internal nodes only store the sum of frequencies."
  }
];

  return <QuizEngine title="Huffman Coding Quiz" questions={questions} />;
};

export default handleNext;
