"use client";
import React from "react";
import QuizEngine from "@/app/components/ui/QuizEngine";

const handleNext = () => {
  const questions = [
  {
    "question": "What is an Abstract Syntax Tree (AST)?",
    "options": [
      "A tree containing all whitespace and comments from source code",
      "A tree representation of the structural meaning of source code",
      "A tree used only for sorting algorithms",
      "A tree used to store compiled machine code directly"
    ],
    "correctAnswer": 1,
    "explanation": "An AST represents the abstract syntactic structure of source code, ignoring unnecessary syntax like braces and whitespace."
  },
  {
    "question": "Which phase of a compiler is responsible for creating an AST?",
    "options": [
      "Lexical Analysis",
      "Code Generation",
      "Syntax Analysis (Parsing)",
      "Optimization"
    ],
    "correctAnswer": 2,
    "explanation": "The parsing (Syntax Analysis) phase takes the tokens generated by lexical analysis and arranges them into an AST based on the language's grammar rules."
  },
  {
    "question": "In an AST representing mathematical expressions, what do the leaf nodes typically represent?",
    "options": [
      "Operators (like +, -, *, /)",
      "Operands (like numbers or variables)",
      "Syntax symbols (like parentheses)",
      "Function calls"
    ],
    "correctAnswer": 1,
    "explanation": "Leaf nodes in an expression AST typically contain the operands (values), while internal nodes contain the operators."
  }
];

  return <QuizEngine title="Syntax Trees Quiz" questions={questions} />;
};

export default handleNext;
